# Generated by Django 3.2 on 2021-11-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trabajador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name': 'Trabajadore'},
        ),
    ]
