# Generated by Django 3.2 on 2021-11-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestra', '0002_auto_20211116_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestra',
            name='dependencia',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='maestra',
            name='valor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
