# Generated by Django 3.2 on 2021-11-16 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0001_initial'),
        ('Turista', '0002_alter_turista_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turista',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Persona.persona'),
        ),
    ]
