# Generated by Django 3.2 on 2021-11-16 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestra', '0003_auto_20211116_1325'),
        ('Turista', '0003_alter_turista_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gustos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividades', models.ForeignKey(limit_choices_to={'dependencia': 11}, on_delete=django.db.models.deletion.CASCADE, to='Maestra.maestra')),
                ('turista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gustos', to='Turista.turista')),
            ],
        ),
        migrations.AddField(
            model_name='turista',
            name='actividades',
            field=models.ManyToManyField(through='Turista.Gustos', to='Maestra.Maestra'),
        ),
    ]
