# Generated by Django 3.2 on 2021-11-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Turista', '0004_auto_20211116_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gustos',
            options={'verbose_name': 'Actividades favoritas'},
        ),
    ]
