# Generated by Django 3.2 on 2021-11-16 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestra', '0003_auto_20211116_1325'),
        ('Persona', '0002_persona_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo_documento',
            field=models.ForeignKey( limit_choices_to={'dependecia': 8}, on_delete=django.db.models.deletion.CASCADE, related_name='tipoIden', to='Maestra.maestra'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.ForeignKey(limit_choices_to={'dependecia': 7}, on_delete=django.db.models.deletion.CASCADE, related_name='genero', to='Maestra.maestra'),
        ),
    ]
