# Generated by Django 3.2 on 2021-11-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0003_auto_20211116_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='identidad',
            field=models.CharField(max_length=11, verbose_name='numero de documento'),
        ),
    ]
