# Generated by Django 3.2 on 2021-11-16 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestra', '0003_auto_20211116_1325'),
        ('Persona', '0004_alter_persona_identidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nacionalidad',
            field=models.ForeignKey(limit_choices_to={'dependencia:9'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nacionalidad', to='Maestra.maestra'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.ForeignKey(limit_choices_to={'dependencia': 7}, on_delete=django.db.models.deletion.CASCADE, related_name='genero', to='Maestra.maestra'),
        ),
    ]
