# Generated by Django 3.2 on 2021-11-16 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maestra', '0003_auto_20211116_1325'),
        ('Persona', '0005_auto_20211116_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=models.ForeignKey(limit_choices_to={'dependencia': 9}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nacionalidad', to='Maestra.maestra'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_documento',
            field=models.ForeignKey(limit_choices_to={'dependencia': 8}, on_delete=django.db.models.deletion.CASCADE, related_name='tipoIden', to='Maestra.maestra'),
        ),
    ]
